#!/bin/sh

PREFIX=$HOME/Softwares/darwin-homebrew-gcc-9

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 \
    -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/msgpack-c-cpp-3.3.0 \
    -D MSGPACK_CXX11=ON \
    ../src
