#!/bin/sh

cmake  \
    -D CMAKE_BUILD_TYPE=Release \
    -D TPL_ENABLE_BLAS=ON \
    -D BLAS_LIBRARY_NAMES=openblas \
    -D TPL_ENABLE_LAPACK=ON \
    -D LAPACK_LIBRARY_NAMES=openblas \
    -D TPL_ENABLE_MPI=ON \
    -D Trilinos_ENABLE_CXX11=ON \
    -D Trilinos_ENABLE_Fortran=OFF \
    -D Trilinos_ENABLE_OpenMP=ON \
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
    -D Trilinos_ENABLE_Kokkos=ON \
    -D Trilinos_ENABLE_Teuchos=ON \
    -D Trilinos_ENABLE_Tpetra=ON \
    -D Trilinos_ENABLE_Amesos2=ON \
    -D Trilinos_ENABLE_Ifpack2=ON \
    -D Trilinos_ENABLE_Belos=ON \
    -D Trilinos_ENABLE_Zoltan2=ON \
    ../src
