#!/bin/sh

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 \
    -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 \
    -D CMAKE_INSTALL_PREFIX=$HOME/Softwares/darwin-gcc-9.3.0/metis-5.1.0 \
    -D GKLIB_PATH=$HOME/Softwares/darwin-gcc-9.3.0/metis-5.1.0/src/GKlib \
    -D OPENMP=ON \
    ../src
