#!/bin/sh

PREFIX=$HOME/Softwares/darwin-homebrew-gcc-9

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/lapackpp-2021.04.00 \
    -D blaspp_DIR=$PREFIX/blaspp-2021.04.00/lib/blaspp \
    ../src
