#!/bin/sh

PREFIX=$HOME/Softwares/darwin-homebrew-gcc-9

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 \
    -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/eigen-3.3.9 \
    ../src
