#!/bin/sh

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/sw/arcts/centos7/gcc/8.2.0/bin/gcc \
    -D CMAKE_CXX_COMPILER=/sw/arcts/centos7/gcc/8.2.0/bin/g++ \
    -D CMAKE_INSTALL_PREFIX=$HOME/softwares/greatlakes-gcc-8.2.0/eigen-3.3.9 \
    ../src
