#!/bin/sh

PREFIX=$HOME/Softwares/darwin-appleclang

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/bin/clang \
    -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/eigen-3.3.9 \
    ../src
