#!/bin/sh

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/sw/arcts/centos7/gcc/8.2.0/bin/gcc \
    -D CMAKE_CXX_COMPILER=/sw/arcts/centos7/gcc/8.2.0/bin/g++ \
    -D CMAKE_INSTALL_PREFIX=$HOME/Softwares/greatlakes-gcc-8.2.0/yaml-cpp-0.6.3 \
    -D YAML_CPP_BUILD_TESTS=OFF \
    ../src
