#!/bin/sh

PREFIX=$HOME/Softwares/darwin-homebrew-gcc-9

../src/configure \
    --prefix=$PREFIX/openmpi-4.1.1 \
    CC=/usr/local/bin/gcc-9 \
    CXX=/usr/local/bin/g++-9 \
    FC=/usr/local/bin/gfortran-9
