#!/bin/sh

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=$HOME/Softwares/darwin-gcc-9.3.0/openmpi-4.1.1/bin/mpicc \
    -D CMAKE_CXX_COMPILER=$HOME/Softwares/darwin-gcc-9.3.0/openmpi-4.1.1/bin/mpicxx \
    -D CMAKE_INSTALL_PREFIX=$HOME/Softwares/darwin-gcc-9.3.0/parmetis-4.0.3 \
    -D METIS_PATH=$HOME/Softwares/darwin-gcc-9.3.0/parmetis-4.0.3/src/metis \
    -D GKLIB_PATH=$HOME/Softwares/darwin-gcc-9.3.0/parmetis-4.0.3/src/metis/GKlib \
    -D OPENMP=ON \
    ../src
