#!/bin/sh

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_COMPILER=/sw/arcts/centos7/gcc/8.2.0/bin/g++ \
    -D CMAKE_INSTALL_PREFIX=$HOME/softwares/greatlakes-gcc-8.2.0/blaspp-2021.04.00 \
    -D BLAS_LIBRARIES="-L/sw/arcts/centos7/stacks/gcc/8.2.0/OpenBLAS/0.3.9/lib -lopenblas" \
    ../src
