#!/bin/sh

PREFIX=$HOME/Softwares/darwin-appleclang

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/bin/clang \
    -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/vtk-8.2.0 \
    -D VTK_PYTHON_VERSION=3 \
    ../src
