#!/bin/sh

PREFIX=$HOME/Softwares/darwin-appleclang

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER=/usr/bin/clang \
    -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/yaml-cpp-0.6.3 \
    -D YAML_CPP_BUILD_TESTS=OFF \
    ../src
