#!/bin/sh

PREFIX=$HOME/Softwares/darwin-appleclang

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -D CMAKE_INSTALL_PREFIX=$PREFIX/blaspp-2021.04.00 \
    -D build_tests=OFF \
    ../src
